#!/usr/bin/env bash
set -euo pipefail

: "${XHAND_DATA_ROOT:?Set XHAND_DATA_ROOT}"
: "${XHAND_ACTION_STATS_PATH:?Set XHAND_ACTION_STATS_PATH}"
: "${ZEVA_POLICY_CHECKPOINT:?Set ZEVA_POLICY_CHECKPOINT}"
: "${ZEVA_FEATURE_CACHE:?Set ZEVA_FEATURE_CACHE}"
: "${TACTILE_ENCODER_CHECKPOINT:?Set TACTILE_ENCODER_CHECKPOINT}"
: "${WAN_VAE_PATH:?Set WAN_VAE_PATH}"

export XHAND_DATA_ROOT XHAND_ACTION_STATS_PATH ZEVA_POLICY_CHECKPOINT ZEVA_FEATURE_CACHE TACTILE_ENCODER_CHECKPOINT WAN_VAE_PATH
TOML_FILE="examples/toml/sft_config/action_policy_xhand_zeva_tactile.toml"
if [[ -n "${ZEVA_TACTILE_TAIL_OVERRIDES:-}" ]]; then
  read -r -a TAIL_OVERRIDES <<< "$ZEVA_TACTILE_TAIL_OVERRIDES"
fi
source "$(dirname "${BASH_SOURCE[0]}")/_sft_launcher_common.sh"
