#!/usr/bin/env bash
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: OpenMDW-1.1

# ============================================================================
# Structured-TOML launch for UR7e + XHand action-policy SFT on Cosmos3-Nano.
# Drives cosmos_framework.scripts.train against
# examples/toml/sft_config/action_policy_xhand_nano.toml (selects the registered
# `action_policy_xhand_nano` experiment; 18-dim joint-position actions at 15 fps,
# starting from a post-trained policy so its action heads are kept).
#
# Env vars (override for your filesystem):
#   XHAND_DATA_ROOT         Root of the converted LeRobot tree
#                           (<root>/<category>/<task>/<x>/lerobot/meta/info.json).
#                           tools/convert_xhand_dataset.py produces this layout.
#   XHAND_ACTION_STATS_PATH meta/feature_stats_compact.json of that dataset
#                           (generated by the same converter; drives minmax
#                           action normalization).
#   BASE_CHECKPOINT_PATH    DCP of nvidia/Cosmos3-Nano-Policy-DROID
#                           (convert_model_to_dcp; see docs/action_policy_droid_posttrain.md).
#   WAN_VAE_PATH            Wan2.2 VAE .pth (Wan-AI/Wan2.2-TI2V-5B)
#   NPROC_PER_NODE          torchrun --nproc_per_node (default 8)
#   TAIL_OVERRIDES          bash array of Hydra CLI overrides (see _sft_launcher_common.sh)
#
# Single-node smoke (config/data sanity, a few iters):
#   TAIL_OVERRIDES=(trainer.max_iter=10 checkpoint.save_iter=10 \
#                   dataloader_train.max_samples_per_batch=8) \
#     bash examples/launch_sft_action_policy_xhand_nano.sh
# ============================================================================

TOML_FILE="examples/toml/sft_config/action_policy_xhand_nano.toml"

: "${XHAND_DATA_ROOT:?Set XHAND_DATA_ROOT to the converted LeRobot tree}"
: "${XHAND_ACTION_STATS_PATH:?Set XHAND_ACTION_STATS_PATH to meta/feature_stats_compact.json}"
: "${BASE_CHECKPOINT_PATH:?Set BASE_CHECKPOINT_PATH to the Cosmos3-Nano-Policy-DROID DCP dir}"
: "${WAN_VAE_PATH:?Set WAN_VAE_PATH to the Wan2.2 VAE checkpoint}"

export XHAND_DATA_ROOT XHAND_ACTION_STATS_PATH BASE_CHECKPOINT_PATH WAN_VAE_PATH

EXTRA_DATASET_CHECK='
# NOTE: use [ ] not [[ ]] for the glob — [[ ]] suppresses pathname expansion,
# so the pattern would stay literal and the test would always fail.
compgen -G "$XHAND_DATA_ROOT"/*/*/*/lerobot/meta/info.json >/dev/null || {
  echo "ERROR: no <root>/<category>/<task>/<x>/lerobot/meta/info.json under $XHAND_DATA_ROOT" >&2
  echo "       run: python tools/convert_xhand_dataset.py" >&2
  exit 1
}
[ -f "$XHAND_ACTION_STATS_PATH" ] || { echo "ERROR: missing $XHAND_ACTION_STATS_PATH" >&2; exit 1; }
[ -f "$WAN_VAE_PATH" ] || { echo "ERROR: missing $WAN_VAE_PATH" >&2; exit 1; }
'

source "$(dirname "${BASH_SOURCE[0]}")/_sft_launcher_common.sh"
